### ISSUE TITLE
Timeout of -1 does not work in old Eclipser

### ISSUE THREAD

**Issue by agroce** [SoftSec-KAIST/Eclipser#21]
The argument is passed on to 'System.TimeSpan' and results in:

```
Parameter name: timeout
   at System.Threading.Thread.ToTimeoutMilliseconds(TimeSpan timeout)
   at Eclipser.Fuzz.fuzzingTimer@121.Invoke(Unit unitVar) in /root/Eclipser/src/Fuzz/Fuzz.fs:line 122
   at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvoke[T,TResult](AsyncActivation`1 ctxt, TResult result1, FSharpFunc`2 part2)
   at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.FSharp.Control.AsyncPrimitives.Start@938-1.Invoke(ExceptionDispatchInfo edi)
   at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction)
   at <StartupCode$FSharp-Core>.$Async.-ctor@167-1.Invoke(Object o)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
Aborted
```

https://github.com/SoftSec-KAIST/Eclipser/pull/20 fixes it the same way as it is fixed in master (just not starting a timeout when using -1)

**Comment by jchoi2022** [comment]
Thank you for the pull request. I merged it and now Eclipser v1.x can handle a negative timeout value, too.
